---
layout: default
title: MintCoinCrypto
---

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ page.title }}</title>
    <link rel="stylesheet" href="{{ site.baseurl }}/assets/css/style.css">
</head>
<body>
    <header>
        <h1>{{ site.title }}</h1>
        <nav>
            <ul>
                <li><a href="{{ site.baseurl }}">Home</a></li>
                <!-- Add links to other pages -->
            </ul>
        </nav>
    </header>

    <main>
        <h2>Welcome to {{ site.title }}</h2>
        <p>Your gateway to a decentralized future!</p>
        <div class="token-info">
            <p>Total Supply: {{ site.supply }}</p>
            <p>Token Type: {{ site.token_type }}</p>
            <p>Wallet Status: {{ site.wallet_status }}</p>
        </div>
        <!-- Add more content here -->
    </main>

    <footer>
        <p>&copy; {{ site.author }} {{ site.year }}</p>
    </footer>

    <script src="{{ site.baseurl }}/assets/js/script.js"></script>
</body>
</html>
